app = 'firefox-flyio'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
